// sw.js — offline cache. Same recipe as the metronome/fretboard siblings.
// IMPORTANT: bump CACHE on any file change, and keep ASSETS listing EVERY shipped
// file (cache-first means anything not listed is unavailable offline).
const CACHE = "sn-v31";

const ASSETS = [
  "./",
  "./index.html",
  "./styles.css",
  "./manifest.webmanifest",
  "./js/main.js",
  "./js/ui.js",
  "./js/dom.js",
  "./js/songsView.js",
  "./js/persistence.js",
  "./js/session.js",
  "./js/derive.js",
  "./js/feels.js",
  "./js/feelStore.js",
  "./js/songs.js",
  "./js/songStore.js",
  "./js/sketches.js",
  "./js/audioStore.js",
  "./js/sketchesView.js",
  "./js/tape/takeModel.js",
  "./js/tape/meterModel.js",
  "./js/tape/clickModel.js",
  "./js/tape/click.js",
  "./js/tape/wav.js",
  "./js/tape/lufs.js",
  "./js/tape/limiter.js",
  "./js/tape/latency.js",
  "./js/tape/audioEngine.js",
  "./js/tape/takeStore.js",
  "./js/tape/opfsWorker.js",
  "./js/tape/captureProcessor.js",
  "./js/tape/devices.js",
  "./js/tape/deckControls.js",
  "./js/tape/tapeView.js",
  "./js/tape/drumModel.js",
  "./js/tape/midiParse.js",
  "./js/tape/drumKits.js",
  "./js/tape/drumMachine.js",
  "./js/tape/drumPanel.js",
  // drum machine samples — CC-BY/CC0, see assets/drums/CREDITS.md
  "./assets/drums/kits/kit4/kick.wav",
  "./assets/drums/kits/kit4/snare.wav",
  "./assets/drums/kits/kit4/closedHat.wav",
  "./assets/drums/kits/kit4/openHat.wav",
  "./assets/drums/kits/kit4/lowTom.wav",
  "./assets/drums/kits/kit4/midTom.wav",
  "./assets/drums/kits/kit4/highTom.wav",
  "./assets/drums/kits/kit4/crash.wav",
  "./assets/drums/kits/kit4/ride.wav",
  "./assets/drums/kits/kit4/clap.wav",
  "./assets/drums/kits/kit4/hiConga.wav",
  "./assets/drums/kits/kit4/loConga.wav",
  "./js/theory/pitch.js",
  "./js/theory/spell.js",
  "./js/theory/scale.js",
  "./js/theory/chord.js",
  "./js/theory/roman.js",
  "./js/data/modes.js",
  "./js/generators/section.js",
  "./js/generators/mainProgression.js",
  "./js/generators/alternatives.js",
  "./js/generators/index.js",
  // feels:start (generated by tools/sync-feels.js — do not edit by hand)
  "./feels/index.json",
  "./feels/alternative.json",
  "./feels/canon.json",
  "./feels/cliche.json",
  "./feels/cliche2.json",
  "./feels/endless.json",
  "./feels/energetic.json",
  "./feels/grungy.json",
  "./feels/memories.json",
  "./feels/rebellious.json",
  "./feels/sad.json",
  "./feels/simple.json",
  "./feels/simple2.json",
  "./feels/twelve-bar-blues.json",
  "./feels/wistful.json",
  "./feels/doo-wop-2.json",
  "./feels/doo-wop.json",
  "./feels/spector-girl-groups.json",
  "./feels/dark-folk.json",
  "./feels/menace-drone.json",
  "./feels/red-right-hand.json",
  "./feels/like-a-rolling-stone.json",
  "./feels/simple-twist.json",
  "./feels/watchtower.json",
  // feels:end
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-512.png",
  "./icons/apple-touch-icon.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((resp) => {
          if (resp && resp.status === 200 && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return resp;
        })
        .catch(() => {
          if (req.mode === "navigate") {
            return caches.match("./index.html", { ignoreSearch: true })
              .then((c) => c || caches.match("./", { ignoreSearch: true }));
          }
        });
    })
  );
});
