// sw.js — offline cache. Same recipe as the metronome/fretboard siblings.
// IMPORTANT: bump CACHE on any file change, and keep ASSETS listing EVERY shipped
// file (cache-first means anything not listed is unavailable offline).
const CACHE = "sn-v8";

const ASSETS = [
  "./",
  "./index.html",
  "./styles.css",
  "./manifest.webmanifest",
  "./js/main.js",
  "./js/ui.js",
  "./js/persistence.js",
  "./js/session.js",
  "./js/derive.js",
  "./js/feels.js",
  "./js/feelStore.js",
  "./js/theory/pitch.js",
  "./js/theory/spell.js",
  "./js/theory/scale.js",
  "./js/theory/chord.js",
  "./js/data/modes.js",
  "./js/generators/section.js",
  "./js/generators/mainProgression.js",
  "./js/generators/alternatives.js",
  "./js/generators/index.js",
  // feels:start (generated by tools/sync-feels.js — do not edit by hand)
  "./feels/index.json",
  "./feels/alternative.json",
  "./feels/canon.json",
  "./feels/cliche.json",
  "./feels/cliche2.json",
  "./feels/creepy.json",
  "./feels/creepy2.json",
  "./feels/endless.json",
  "./feels/energetic.json",
  "./feels/grungy.json",
  "./feels/memories.json",
  "./feels/rebellious.json",
  "./feels/sad.json",
  "./feels/simple.json",
  "./feels/simple2.json",
  "./feels/twelve-bar-blues.json",
  "./feels/wistful.json",
  // feels:end
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-512.png",
  "./icons/apple-touch-icon.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((resp) => {
          if (resp && resp.status === 200 && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return resp;
        })
        .catch(() => {
          if (req.mode === "navigate") {
            return caches.match("./index.html", { ignoreSearch: true })
              .then((c) => c || caches.match("./", { ignoreSearch: true }));
          }
        });
    })
  );
});
