// sw.js — offline cache. Same recipe as the metronome/fretboard siblings.
// IMPORTANT: bump CACHE on any file change, and keep ASSETS listing EVERY shipped
// file (cache-first means anything not listed is unavailable offline).
const CACHE = "sn-v41";

const ASSETS = [
  "./",
  "./index.html",
  "./theme.css",
  "./styles.css",
  "./manifest.webmanifest",
  "./js/main.js",
  "./js/ui.js",
  "./js/dom.js",
  "./js/songsView.js",
  "./js/persistence.js",
  "./js/session.js",
  "./js/derive.js",
  "./js/feels.js",
  "./js/feelStore.js",
  "./js/songs.js",
  "./js/songStore.js",
  "./js/sketches.js",
  "./js/audioStore.js",
  "./js/sketchesView.js",
  "./js/tape/takeModel.js",
  "./js/tape/meterModel.js",
  "./js/tape/clickModel.js",
  "./js/tape/click.js",
  "./js/tape/wav.js",
  "./js/tape/lufs.js",
  "./js/tape/limiter.js",
  "./js/tape/latency.js",
  "./js/tape/audioEngine.js",
  "./js/tape/takeStore.js",
  "./js/tape/folderStore.js",
  "./js/tape/opfsWorker.js",
  "./js/tape/captureProcessor.js",
  "./js/tape/devices.js",
  "./js/tape/deckControls.js",
  "./js/tape/tapeView.js",
  "./js/tape/drumModel.js",
  "./js/tape/midiParse.js",
  "./js/tape/drumKits.js",
  "./js/tape/drumMachine.js",
  "./js/tape/drumPanel.js",
  "./js/tape/rulesetModel.js",
  "./js/tape/rulesetStore.js",
  "./js/tape/loopFolder.js",
  "./js/tape/loopPicker.js",
  // drum-loop sequencer starter rulesets (user-authored ones live in localStorage)
  "./assets/rulesets/index.json",
  "./assets/rulesets/wander-65.json",
  "./assets/rulesets/even-bag.json",
  "./assets/rulesets/round-robin.json",
  // drum machine samples + reverb impulses — CC-BY/CC0, see assets/drums/CREDITS.md
  "./assets/drums/kits/abeyroad/clap.wav",
  "./assets/drums/kits/abeyroad/closedHat.wav",
  "./assets/drums/kits/abeyroad/crash.wav",
  "./assets/drums/kits/abeyroad/hiConga.wav",
  "./assets/drums/kits/abeyroad/highTom.wav",
  "./assets/drums/kits/abeyroad/kick.wav",
  "./assets/drums/kits/abeyroad/loConga.wav",
  "./assets/drums/kits/abeyroad/lowTom.wav",
  "./assets/drums/kits/abeyroad/midTom.wav",
  "./assets/drums/kits/abeyroad/openHat.wav",
  "./assets/drums/kits/abeyroad/ride.wav",
  "./assets/drums/kits/abeyroad/snare.wav",
  "./assets/drums/kits/currentz/clap.wav",
  "./assets/drums/kits/currentz/closedHat.wav",
  "./assets/drums/kits/currentz/crash.wav",
  "./assets/drums/kits/currentz/hiConga.wav",
  "./assets/drums/kits/currentz/highTom.wav",
  "./assets/drums/kits/currentz/kick.wav",
  "./assets/drums/kits/currentz/loConga.wav",
  "./assets/drums/kits/currentz/lowTom.wav",
  "./assets/drums/kits/currentz/midTom.wav",
  "./assets/drums/kits/currentz/openHat.wav",
  "./assets/drums/kits/currentz/ride.wav",
  "./assets/drums/kits/currentz/snare.wav",
  "./assets/drums/kits/demarco/clap.wav",
  "./assets/drums/kits/demarco/closedHat.wav",
  "./assets/drums/kits/demarco/crash.wav",
  "./assets/drums/kits/demarco/hiConga.wav",
  "./assets/drums/kits/demarco/highTom.wav",
  "./assets/drums/kits/demarco/kick.wav",
  "./assets/drums/kits/demarco/loConga.wav",
  "./assets/drums/kits/demarco/lowTom.wav",
  "./assets/drums/kits/demarco/midTom.wav",
  "./assets/drums/kits/demarco/openHat.wav",
  "./assets/drums/kits/demarco/ride.wav",
  "./assets/drums/kits/demarco/snare.wav",
  "./assets/drums/kits/fleetwood/clap.wav",
  "./assets/drums/kits/fleetwood/closedHat.wav",
  "./assets/drums/kits/fleetwood/crash.wav",
  "./assets/drums/kits/fleetwood/hiConga.wav",
  "./assets/drums/kits/fleetwood/highTom.wav",
  "./assets/drums/kits/fleetwood/kick.wav",
  "./assets/drums/kits/fleetwood/loConga.wav",
  "./assets/drums/kits/fleetwood/lowTom.wav",
  "./assets/drums/kits/fleetwood/midTom.wav",
  "./assets/drums/kits/fleetwood/openHat.wav",
  "./assets/drums/kits/fleetwood/ride.wav",
  "./assets/drums/kits/fleetwood/snare.wav",
  "./assets/drums/kits/harvest/clap.wav",
  "./assets/drums/kits/harvest/closedHat.wav",
  "./assets/drums/kits/harvest/crash.wav",
  "./assets/drums/kits/harvest/hiConga.wav",
  "./assets/drums/kits/harvest/highTom.wav",
  "./assets/drums/kits/harvest/kick.wav",
  "./assets/drums/kits/harvest/loConga.wav",
  "./assets/drums/kits/harvest/lowTom.wav",
  "./assets/drums/kits/harvest/midTom.wav",
  "./assets/drums/kits/harvest/openHat.wav",
  "./assets/drums/kits/harvest/ride.wav",
  "./assets/drums/kits/harvest/snare.wav",
  "./assets/drums/kits/jazzfunk/clap.wav",
  "./assets/drums/kits/jazzfunk/closedHat.wav",
  "./assets/drums/kits/jazzfunk/crash.wav",
  "./assets/drums/kits/jazzfunk/hiConga.wav",
  "./assets/drums/kits/jazzfunk/highTom.wav",
  "./assets/drums/kits/jazzfunk/kick.wav",
  "./assets/drums/kits/jazzfunk/loConga.wav",
  "./assets/drums/kits/jazzfunk/lowTom.wav",
  "./assets/drums/kits/jazzfunk/midTom.wav",
  "./assets/drums/kits/jazzfunk/openHat.wav",
  "./assets/drums/kits/jazzfunk/ride.wav",
  "./assets/drums/kits/jazzfunk/snare.wav",
  "./assets/drums/kits/kit4/clap.wav",
  "./assets/drums/kits/kit4/closedHat.wav",
  "./assets/drums/kits/kit4/crash.wav",
  "./assets/drums/kits/kit4/hiConga.wav",
  "./assets/drums/kits/kit4/highTom.wav",
  "./assets/drums/kits/kit4/kick.wav",
  "./assets/drums/kits/kit4/loConga.wav",
  "./assets/drums/kits/kit4/lowTom.wav",
  "./assets/drums/kits/kit4/midTom.wav",
  "./assets/drums/kits/kit4/openHat.wav",
  "./assets/drums/kits/kit4/ride.wav",
  "./assets/drums/kits/kit4/snare.wav",
  "./assets/drums/kits/seachange/clap.wav",
  "./assets/drums/kits/seachange/closedHat.wav",
  "./assets/drums/kits/seachange/crash.wav",
  "./assets/drums/kits/seachange/hiConga.wav",
  "./assets/drums/kits/seachange/highTom.wav",
  "./assets/drums/kits/seachange/kick.wav",
  "./assets/drums/kits/seachange/loConga.wav",
  "./assets/drums/kits/seachange/lowTom.wav",
  "./assets/drums/kits/seachange/midTom.wav",
  "./assets/drums/kits/seachange/openHat.wav",
  "./assets/drums/kits/seachange/ride.wav",
  "./assets/drums/kits/seachange/snare.wav",
  "./assets/drums/kits/wreckingcrew/clap.wav",
  "./assets/drums/kits/wreckingcrew/closedHat.wav",
  "./assets/drums/kits/wreckingcrew/crash.wav",
  "./assets/drums/kits/wreckingcrew/hiConga.wav",
  "./assets/drums/kits/wreckingcrew/highTom.wav",
  "./assets/drums/kits/wreckingcrew/kick.wav",
  "./assets/drums/kits/wreckingcrew/loConga.wav",
  "./assets/drums/kits/wreckingcrew/lowTom.wav",
  "./assets/drums/kits/wreckingcrew/midTom.wav",
  "./assets/drums/kits/wreckingcrew/openHat.wav",
  "./assets/drums/kits/wreckingcrew/ride.wav",
  "./assets/drums/kits/wreckingcrew/snare.wav",
  "./assets/drums/ir/largehall.wav",
  "./assets/drums/ir/mediumhall1.wav",
  "./assets/drums/ir/mediumhall2.wav",
  "./assets/drums/ir/room1.wav",
  "./assets/drums/ir/room2.wav",
  "./assets/drums/ir/spring.wav",
  "./assets/drums/ir/studio.wav",
  "./assets/drums/ir/underground.wav",
  "./js/theory/pitch.js",
  "./js/theory/spell.js",
  "./js/theory/scale.js",
  "./js/theory/chord.js",
  "./js/theory/roman.js",
  "./js/data/modes.js",
  "./js/generators/section.js",
  "./js/generators/mainProgression.js",
  "./js/generators/alternatives.js",
  "./js/generators/index.js",
  // feels:start (generated by tools/sync-feels.js — do not edit by hand)
  "./feels/index.json",
  "./feels/alternative.json",
  "./feels/canon.json",
  "./feels/cliche.json",
  "./feels/cliche2.json",
  "./feels/endless.json",
  "./feels/energetic.json",
  "./feels/grungy.json",
  "./feels/memories.json",
  "./feels/rebellious.json",
  "./feels/sad.json",
  "./feels/simple.json",
  "./feels/simple2.json",
  "./feels/twelve-bar-blues.json",
  "./feels/wistful.json",
  "./feels/doo-wop-2.json",
  "./feels/doo-wop.json",
  "./feels/spector-girl-groups.json",
  "./feels/dark-folk.json",
  "./feels/menace-drone.json",
  "./feels/red-right-hand.json",
  "./feels/like-a-rolling-stone.json",
  "./feels/simple-twist.json",
  "./feels/watchtower.json",
  // feels:end
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/maskable-512.png",
  "./icons/apple-touch-icon.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (event) => {
  const req = event.request;
  if (req.method !== "GET") return;
  event.respondWith(
    caches.match(req).then((cached) => {
      if (cached) return cached;
      return fetch(req)
        .then((resp) => {
          if (resp && resp.status === 200 && resp.type === "basic") {
            const copy = resp.clone();
            caches.open(CACHE).then((cache) => cache.put(req, copy));
          }
          return resp;
        })
        .catch(() => {
          if (req.mode === "navigate") {
            return caches.match("./index.html", { ignoreSearch: true })
              .then((c) => c || caches.match("./", { ignoreSearch: true }));
          }
        });
    })
  );
});
